// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwS6YNFCB0On8IFiBXHeDm1xM63fyvo0',
    appId: '1:414039941445:web:412a5ccc3e6e2654a2de2c',
    messagingSenderId: '414039941445',
    projectId: 'petshop-87aa4',
    authDomain: 'petshop-87aa4.firebaseapp.com',
    storageBucket: 'petshop-87aa4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtk0OhpgxuGELXw6eHlfg1QbomUyXNdWs',
    appId: '1:414039941445:android:f2060b1a9c92c1f4a2de2c',
    messagingSenderId: '414039941445',
    projectId: 'petshop-87aa4',
    storageBucket: 'petshop-87aa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQIbAyNIEkA4Z9Dq2GSp9ffMrPtymbCU',
    appId: '1:414039941445:ios:2e13b6eb9fffd273a2de2c',
    messagingSenderId: '414039941445',
    projectId: 'petshop-87aa4',
    storageBucket: 'petshop-87aa4.appspot.com',
    androidClientId: '414039941445-51lels07i1e6gj75u02i1p1jm5m2lfe4.apps.googleusercontent.com',
    iosClientId: '414039941445-sj3enfdd7blj6n43dcdk2nsgna4nmb5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectPetShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNQIbAyNIEkA4Z9Dq2GSp9ffMrPtymbCU',
    appId: '1:414039941445:ios:2e13b6eb9fffd273a2de2c',
    messagingSenderId: '414039941445',
    projectId: 'petshop-87aa4',
    storageBucket: 'petshop-87aa4.appspot.com',
    androidClientId: '414039941445-51lels07i1e6gj75u02i1p1jm5m2lfe4.apps.googleusercontent.com',
    iosClientId: '414039941445-sj3enfdd7blj6n43dcdk2nsgna4nmb5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectPetShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgwS6YNFCB0On8IFiBXHeDm1xM63fyvo0',
    appId: '1:414039941445:web:fbed8306f798569ba2de2c',
    messagingSenderId: '414039941445',
    projectId: 'petshop-87aa4',
    authDomain: 'petshop-87aa4.firebaseapp.com',
    storageBucket: 'petshop-87aa4.appspot.com',
  );

}